title: Reckoning with Racial Fascism
description: A Seminar in Theories of Cultural Studies — CSA 2022

url: http://sgotzler.github.com/reckoning-csa
baseurl: "/reckoning-csa"
paginate_path: "blog/page:num/"
permalink: blog/:title/

header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Cultural Studies Association (U.S.) — 20th Annual Conference, 2022
    url: https://www.culturalstudiesassociation.org/conference.html

social:
  github: sgotzler
  twitter: steevegotz

google_analytics: "UA-58263416-1"

disqus:
    shortname:
